# Generated by Django 4.2.13 on 2024-06-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamimi_admin', '0012_alter_parentsectionmodel_parentsectionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentsectionmodel',
            name='parentsectionimage',
            field=models.ImageField(blank=True, null=True, upload_to='parentsectionimages/'),
        ),
    ]
