# Generated by Django 4.2.13 on 2024-06-26 08:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tamimi_admin', '0013_alter_parentsectionmodel_parentsectionimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentsectionmodel',
            name='parentsectionimage',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='parentsectionimages/'),
            preserve_default=False,
        ),
    ]
