# Generated by Django 4.2.13 on 2024-07-18 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tamimi_admin', '0015_deviceordermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicemodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tamimi_admin.categorymodel'),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tamimi_admin.categorymodel'),
        ),
    ]
