# Generated by Django 4.2.13 on 2024-07-22 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tamimi_admin', '0016_alter_devicemodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceordermodel',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tamimi_admin.devicemodel'),
        ),
    ]
