# Generated by Django 4.2.13 on 2024-07-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamimi_admin', '0018_deviceordermodel_sortno'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devicecount', models.IntegerField(default=0)),
                ('sectioncount', models.IntegerField(default=0)),
            ],
        ),
    ]
