# Generated by Django 4.2.13 on 2024-07-24 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tamimi_admin', '0019_countmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionOrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sortno', models.IntegerField()),
                ('parent', models.BooleanField()),
                ('child', models.BooleanField()),
                ('childsection', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tamimi_admin.sectionmodel')),
                ('parentsection', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tamimi_admin.parentsectionmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='CountModel',
        ),
    ]
