# Generated by Django 4.2.13 on 2024-07-25 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamimi_admin', '0020_sectionordermodel_delete_countmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionordermodel',
            old_name='child',
            new_name='section',
        ),
    ]
