# Generated by Django 4.2.13 on 2024-07-25 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamimi_admin', '0021_rename_child_sectionordermodel_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionordermodel',
            name='section',
        ),
    ]
