# Generated by Django 4.2.13 on 2024-07-27 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tamimi_admin', '0022_remove_sectionordermodel_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionordermodel',
            old_name='childsection',
            new_name='normalsection',
        ),
    ]
